// THIS FILE IS AUTO GENERATED

/* eslint-disable */

export enum IconNames {
  'add' = 'add',
  'arrowForward' = 'arrowForward',
  'breadcrum' = 'breadcrum',
  'bus_placeholder' = 'bus_placeholder',
  'check' = 'check',
  'close' = 'close',
  'closed' = 'closed',
  'delete' = 'delete',
  'destination_point' = 'destination_point',
  'down' = 'down',
  'download' = 'download',
  'empty-search-state' = 'empty-search-state',
  'eye' = 'eye',
  'greater' = 'greater',
  'info' = 'info',
  'info_2' = 'info_2',
  'invoice' = 'invoice',
  'location' = 'location',
  'mail' = 'mail',
  'next' = 'next',
  'next2' = 'next2',
  'next_arrow' = 'next_arrow',
  'open-eye' = 'open-eye',
  'pause' = 'pause',
  'pdf_download' = 'pdf_download',
  'phone' = 'phone',
  'play' = 'play',
  'prev' = 'prev',
  'prev_arrow' = 'prev_arrow',
  'previewUrl' = 'previewUrl',
  'red-trash' = 'red-trash',
  'source_point' = 'source_point',
  'v-dot' = 'v-dot',
  'vehicle_icon' = 'vehicle_icon',
  'warning' = 'warning'
}
