import { test } from '@playwright/test'
import { login } from '../auth/utils'

test.beforeEach(async ({ page }) => {
  await login(page)
})
test.describe('view users active booking details', () => {
    test('view users active booking details', async ({ page }) => {
      await page.goto('http://localhost:3000/users/49703/active-bookings')

      await page.route('**/v1/users/49703/routes', (route) => {
        route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(
            {
              data: [
                  {
                      id: 913387,
                      user_id: 49691,
                      route_id: 927,
                      user_route_id: 625706,
                      days_ids: '[2]',
                      created_at: '2024-02-12 08:43:38',
                      updated_at: '2024-02-12 09:44:18',
                      day_id: 2,
                      trip_date: '2024-02-12',
                      trip_id: 59128,
                      luggage_quantity: 0,
                      payment_source: 'main_balance',
                      unit_cost: 840,
                      passenger_name: 'someone somewhere',
                      restored_at: null,
                      deleted_at: null,
                      status: 'COMPLETED',
                      check_in_status: 'pending',
                      vehicle_id: 497,
                      route_itinerary_id: 3349,
                      route_day_id: 4960442,
                      bus_pass: 'AGO225-03',
                      is_multiple_seats_booking: 0,
                      passenger_json: {
                          email: 'hello@mailinator.com',
                          fname: 'someone',
                          lname: 'somewhere',
                          phone: '08106362749',
                          fullname: 'someone somewhere'
                      },
                      bus_captain_id: null,
                      is_refunded: 0,
                      cancellation_reason: null,
                      instant_payment_provider: 'paystack',
                      corporate_id: null,
                      meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":340,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":840,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960442,"actualChargeToBeRemitted":500,"paymentReference":null}]}',
                      unit_cost_before_additional_charges: '340.00',
                      userRoute: {
                          id: 625706,
                          user_id: 49691,
                          route_id: 927,
                          pickup_id: 128601,
                          destination_id: 128611,
                          itinerary_id: 3349,
                          created_at: '2024-02-12 08:43:38',
                          updated_at: '2024-02-12 09:44:18',
                          recurring: 0,
                          current_week: 1,
                          bus_pass: 'AGLE568',
                          cost: 840,
                          start_date: '2024-02-12 00:00:00',
                          end_date: '2024-02-12 00:00:00',
                          with_return_trip: 0,
                          deleted_at: null,
                          is_checked_in: 0,
                          booking_status: 'completed',
                          origin_point: null,
                          destination_point: null,
                          pickup_route_bus_stop_id: 128601,
                          destination_route_bus_stop_id: 128611,
                          origin_label: 'West End Bus Stop',
                          destination_label: '1004 First Gate Bus Stop',
                          selected_days: [
                              'Monday'
                          ],
                          booked_from: null,
                          booked_by: 49691,
                          booked_by_admin_id: 56,
                          booked_by_user_type: null,
                          itinerary: {
                              id: 3349,
                              pickup_id: 3724,
                              route_id: 927,
                              departure_time: '09:40',
                              time_of_day: 'AM',
                              created_at: '2022-05-27 09:54:40',
                              updated_at: '2024-02-12 09:25:38',
                              restored_at: null,
                              deleted_at: null,
                              default_fare: 900,
                              default_fare_currency: 'NGN',
                              trip_time_in_hours: 94000,
                              pricing_scheme: 'per_seat',
                              pricing_margin: 20,
                              pricing_margin_unit: 'percent',
                              pricing_type: 'margin_value_generated',
                              break_even_utilization: 0.7,
                              payment_mode: 'pre-trip',
                              payer: 'passenger',
                              itinerary_pair_id: null,
                              trip_time: '09:40 AM'
                          },
                          pickupRouteBusStop: {
                              id: 128601,
                              name: 'West End Bus Stop',
                              geometry: {
                                  x: 3.3752059936523438,
                                  y: 6.5520638101781925
                              },
                              route_id: 927,
                              previous_route_bus_stop: null,
                              next_route_bus_stop: null,
                              place_id: 'manually_planted_bus_stop_1653643777159_CTp2eiUz4',
                              created_at: '2022-05-27 09:29:37',
                              updated_at: '2022-07-25 18:48:44',
                              restored_at: null,
                              deleted_at: null,
                              city_id: 25,
                              position: 14,
                              h3_km5_area_hash: '87589c9a0ffffff',
                              h3_m50_area_hash: '8d589c9a042843f',
                              is_pickup: 1,
                              is_dropoff: 1
                          },
                          destinationRouteBusStop: {
                              id: 128611,
                              name: '1004 First Gate Bus Stop',
                              geometry: {
                                  x: 3.4319400787353516,
                                  y: 6.439761190355234
                              },
                              route_id: 927,
                              previous_route_bus_stop: null,
                              next_route_bus_stop: null,
                              place_id: 'manually_planted_bus_stop_1653644262722_kchDv6xy5H',
                              created_at: '2022-05-27 09:37:43',
                              updated_at: '2022-07-25 18:48:15',
                              restored_at: null,
                              deleted_at: null,
                              city_id: 25,
                              position: 24,
                              h3_km5_area_hash: '87589c99bffffff',
                              h3_m50_area_hash: '8d589c99baf343f',
                              is_pickup: 1,
                              is_dropoff: 1
                          },
                          pickup: {
                              kind: 'pickup',
                              created_at: '2024-02-19 10:56:14',
                              updated_at: '2024-02-19 10:56:14',
                              location: 'West End Bus Stop'
                          },
                          destination: {
                              created_at: '2024-02-19 10:56:14',
                              updated_at: '2024-02-19 10:56:14',
                              location: '1004 First Gate Bus Stop'
                          },
                          driver: {
                              id: 826,
                              vehicle_id: 307,
                              fname: 'MR',
                              lname: 'Solomon',
                              email: 'solomon.shuttlers@gmail.com',
                              phone: '08061924301',
                              avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/driver-826-Kt01TTUxor.jpeg',
                              code: null,
                              active: '1',
                              created_at: '2022-03-27 12:41:58',
                              updated_at: '2023-04-13 11:44:37',
                              city_id: null,
                              login_remote_address: '192.168.69.217',
                              login_date_time: '2022-06-10T00:00:00.000Z',
                              login_is_successful: 1,
                              blocked_reason: null,
                              is_blocked: 0,
                              blocked_at: null,
                              country_code: 'NG',
                              restored_at: null,
                              deleted_at: null,
                              residential_address: null,
                              dob: null,
                              marital_status: null,
                              driving_experience_years: null,
                              gender: null,
                              locality: null,
                              approval_status: 'approved',
                              verified_at: '2022-03-27T11:41:58.000Z',
                              _pivot_driver_id: 826,
                              _pivot_route_itinerary_id: 3349
                          }
                      },
                      route: {
                          id: 927,
                          pickup: 'Ago Roundabout, Okota Road, Lagos, Nigeria',
                          destination: 'Lekki Phase 1, Lagos, Nigeria',
                          pickup_coordinate: '6.5166755, 3.3191264',
                          destination_coordinate: '6.435071199999999, 3.455969',
                          bounds: '{"northeast":{"lat":6.5204005,"lng":3.4560246},"southwest":{"lat":6.4351462,"lng":3.3142191}}',
                          distance: '29.65 km',
                          duration: '55 mins',
                          total_seats: 26,
                          day_of_week: 'MON - FRI',
                          created_at: '2022-05-27 09:54:40',
                          updated_at: '2024-02-12 11:23:45',
                          status: 1,
                          fare: null,
                          visibility: 'public',
                          corporate_id: null,
                          is_future_route: 0,
                          support_luggage: 0,
                          luggage_config_id: null,
                          route_code: 'AGO225',
                          pickup_route_bus_stop_id: 128585,
                          destination_route_bus_stop_id: 128586,
                          is_draft: 0,
                          duration_value: 3326,
                          distance_value: 29646,
                          pickup_geometry: {
                              x: 3.3191264,
                              y: 6.5166755
                          },
                          destination_geometry: {
                              x: 3.455969,
                              y: 6.435071199999999
                          },
                          pickup_search_area_geometry: null,
                          city_id: 25,
                          origin_city_id: 25,
                          destination_city_id: 25,
                          route_availability_days: '["monday","tuesday","wednesday","thursday","friday"]',
                          info: {
                              description: ''
                          },
                          slug: 'ago-roundabout-to-lekki-phase-1-gate',
                          route_availability_start_date: '2023-04-11T00:00:00.000Z',
                          route_availability_end_date: null,
                          blacklisted_availability_days: null,
                          is_exclusive: 0,
                          route_pair_id: null,
                          tag: 'old',
                          shuttle_request_id: null,
                          payer: 'passenger',
                          payment_mode: 'pre-trip',
                          owner_type: 'system',
                          owner_id: null,
                          blacklisted_availability_days_list: []
                      },
                      vehicle: {
                          id: 497,
                          brand: 'Toyota',
                          name: 'Corolla',
                          type: 'Prado SUV',
                          seats: 4,
                          registration_number: 'RTY-123PL',
                          amenities: null,
                          created_at: '2023-11-27 12:37:48',
                          updated_at: '2024-01-29 09:28:55',
                          code: null,
                          tracker_provider_id: 'dfghjk',
                          tracking_id: '0908754567ghjadds',
                          partner_id: 175,
                          vehicle_type_id: 10,
                          year: 2022,
                          status: 'active',
                          license_verification_status: 'not_submitted',
                          owner_driver_id: null,
                          inventory_type: 'regular'
                      },
                      trip: {
                          id: 59128,
                          route_id: 927,
                          driver_id: 1299,
                          start_trip: '2024-02-12 09:26:10',
                          end_trip: '2024-02-12 09:44:18',
                          pickup_coordinate: '6.5166755, 3.3191264',
                          destination_coordinate: '6.5135466666661115, 3.3668908333333337',
                          created_at: '2024-02-12 09:26:10',
                          updated_at: '2024-02-12 09:44:18',
                          route_day_id: 4960442,
                          vehicle_id: 497,
                          cost_of_supply: 800,
                          currency: 'NGN',
                          is_promoted: 0,
                          deleted_at: null,
                          restored_at: null
                      },
                      itinerary: {
                          id: 3349,
                          pickup_id: 3724,
                          route_id: 927,
                          departure_time: '09:40',
                          time_of_day: 'AM',
                          created_at: '2022-05-27 09:54:40',
                          updated_at: '2024-02-12 09:25:38',
                          restored_at: null,
                          deleted_at: null,
                          default_fare: 900,
                          default_fare_currency: 'NGN',
                          trip_time_in_hours: 94000,
                          pricing_scheme: 'per_seat',
                          pricing_margin: 20,
                          pricing_margin_unit: 'percent',
                          pricing_type: 'margin_value_generated',
                          break_even_utilization: 0.7,
                          payment_mode: 'pre-trip',
                          payer: 'passenger',
                          itinerary_pair_id: null,
                          trip_time: '09:40 AM'
                      },
                      pickup: {
                          id: 128601,
                          location: 'West End Bus Stop'
                      },
                      destination: {
                          id: 128611,
                          location: '1004 First Gate Bus Stop'
                      }
                  },
                  {
                      id: 913388,
                      user_id: 49691,
                      route_id: 322,
                      user_route_id: 625707,
                      days_ids: '[2]',
                      created_at: '2024-02-12 08:56:16',
                      updated_at: '2024-02-12 09:31:12',
                      day_id: 2,
                      trip_date: '2024-02-12',
                      trip_id: 59127,
                      luggage_quantity: 0,
                      payment_source: 'main_balance',
                      unit_cost: 1150,
                      passenger_name: 'someone somewhere',
                      restored_at: null,
                      deleted_at: null,
                      status: 'COMPLETED',
                      check_in_status: 'pending',
                      vehicle_id: 357,
                      route_itinerary_id: 1960,
                      route_day_id: 4960417,
                      bus_pass: 'ADD1-02',
                      is_multiple_seats_booking: 0,
                      passenger_json: {
                          email: 'hello@mailinator.com',
                          fname: 'someone',
                          lname: 'somewhere',
                          phone: '08106362749',
                          fullname: 'someone somewhere'
                      },
                      bus_captain_id: null,
                      is_refunded: 0,
                      cancellation_reason: null,
                      instant_payment_provider: 'shuttlers_local_pay',
                      corporate_id: null,
                      meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":650,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":1150,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960417,"actualChargeToBeRemitted":500,"paymentReference":"5e7aca4f-1cf5-4137-9048-790eb2b561b6"}]}',
                      unit_cost_before_additional_charges: '650.00',
                      userRoute: {
                          id: 625707,
                          user_id: 49691,
                          route_id: 322,
                          pickup_id: 98172,
                          destination_id: 98158,
                          itinerary_id: 1960,
                          created_at: '2024-02-12 08:56:16',
                          updated_at: '2024-02-12 09:31:12',
                          recurring: 0,
                          current_week: 1,
                          bus_pass: 'ADEV170',
                          cost: 1150,
                          start_date: '2024-02-12 00:00:00',
                          end_date: '2024-02-12 00:00:00',
                          with_return_trip: 0,
                          deleted_at: null,
                          is_checked_in: 0,
                          booking_status: 'completed',
                          origin_point: null,
                          destination_point: null,
                          pickup_route_bus_stop_id: 98172,
                          destination_route_bus_stop_id: 98158,
                          origin_label: 'Living Hope Parish',
                          destination_label: 'Okeira Kekere',
                          selected_days: [
                              'Monday'
                          ],
                          booked_from: 'guest_mode',
                          booked_by: 49691,
                          booked_by_admin_id: null,
                          booked_by_user_type: null,
                          itinerary: {
                              id: 1960,
                              pickup_id: 98167,
                              route_id: 322,
                              departure_time: '09:30',
                              time_of_day: 'AM',
                              created_at: '2021-01-02 20:08:30',
                              updated_at: '2024-02-12 09:13:00',
                              restored_at: null,
                              deleted_at: null,
                              default_fare: 650,
                              default_fare_currency: 'NGN',
                              trip_time_in_hours: 93000,
                              pricing_scheme: 'per_seat',
                              pricing_margin: 20,
                              pricing_margin_unit: 'percent',
                              pricing_type: 'margin_value_generated',
                              break_even_utilization: 0.7,
                              payment_mode: 'pre-trip',
                              payer: 'passenger',
                              itinerary_pair_id: null,
                              trip_time: '09:30 AM'
                          },
                          pickupRouteBusStop: {
                              id: 98172,
                              name: 'Living Hope Parish',
                              geometry: {
                                  x: 3.587931990623474,
                                  y: 6.498442036454704
                              },
                              route_id: 322,
                              previous_route_bus_stop: 98171,
                              next_route_bus_stop: 98173,
                              place_id: 'manually_planted_bus_stop_1634817983226_ZX0VCLMeR',
                              created_at: '2021-12-29 05:01:58',
                              updated_at: '2022-11-07 07:17:17',
                              restored_at: null,
                              deleted_at: null,
                              city_id: 25,
                              position: 1,
                              h3_km5_area_hash: '87589c808ffffff',
                              h3_m50_area_hash: '8d589c808908abf',
                              is_pickup: 1,
                              is_dropoff: 0
                          },
                          destinationRouteBusStop: {
                              id: 98158,
                              name: 'Okeira Kekere',
                              geometry: {
                                  x: 3.582315444946289,
                                  y: 6.492882866551155
                              },
                              route_id: 322,
                              previous_route_bus_stop: 98157,
                              next_route_bus_stop: 98159,
                              place_id: 'manually_planted_bus_stop_1634931114318_g3r9_Nda-',
                              created_at: '2021-12-29 05:01:58',
                              updated_at: '2022-07-25 18:48:24',
                              restored_at: null,
                              deleted_at: null,
                              city_id: 25,
                              position: 4,
                              h3_km5_area_hash: '87589c808ffffff',
                              h3_m50_area_hash: '8d589c808d198bf',
                              is_pickup: 1,
                              is_dropoff: 1
                          },
                          pickup: {
                              kind: 'pickup',
                              created_at: '2024-02-19 10:56:14',
                              updated_at: '2024-02-19 10:56:14',
                              location: 'Living Hope Parish'
                          },
                          destination: {
                              created_at: '2024-02-19 10:56:14',
                              updated_at: '2024-02-19 10:56:14',
                              location: 'Okeira Kekere'
                          },
                          driver: {
                              id: 1,
                              vehicle_id: 90,
                              fname: 'Celestine',
                              lname: 'Edemba',
                              email: 'celestineedemba@gmail.com',
                              phone: '07033933912',
                              avatar: 'https://image.ibb.co/cwZAa6/IMG_20171114_WA0017.jpg',
                              code: 'a35e8df0-f0e6-11ec-a516-2bfd4346a2bb-1',
                              active: '1',
                              created_at: '2018-01-27 05:47:06',
                              updated_at: '2024-01-17 15:51:51',
                              city_id: null,
                              login_remote_address: '172.20.45.181',
                              login_date_time: '2023-10-03T00:00:00.000Z',
                              login_is_successful: 1,
                              blocked_reason: null,
                              is_blocked: 0,
                              blocked_at: null,
                              country_code: 'NG',
                              restored_at: null,
                              deleted_at: null,
                              residential_address: null,
                              dob: null,
                              marital_status: null,
                              driving_experience_years: null,
                              gender: null,
                              locality: null,
                              approval_status: 'pending',
                              verified_at: '2018-01-27T04:47:06.000Z',
                              _pivot_driver_id: 1,
                              _pivot_route_itinerary_id: 1960
                          }
                      },
                      route: {
                          id: 322,
                          pickup: 'Addo Road, Eti-Osa, Lagos, Nigeria',
                          destination: 'EvertyOne Towers, Lagos, Nigeria',
                          pickup_coordinate: '6.483704700000001, 3.5738825',
                          destination_coordinate: '6.434032900000001, 3.443095599999999',
                          bounds: '{"northeast":{"lat":6.4979779,"lng":3.5855629},"southwest":{"lat":6.4301878,"lng":3.43926}}',
                          distance: '24.17 km',
                          duration: '48 mins',
                          total_seats: 20,
                          day_of_week: 'MON - FRI',
                          created_at: '2020-12-28 16:15:10',
                          updated_at: '2024-02-12 11:23:45',
                          status: 1,
                          fare: null,
                          visibility: 'public',
                          corporate_id: null,
                          is_future_route: 0,
                          support_luggage: 0,
                          luggage_config_id: null,
                          route_code: 'ADD1',
                          pickup_route_bus_stop_id: 98172,
                          destination_route_bus_stop_id: 98248,
                          is_draft: 0,
                          duration_value: 2871,
                          distance_value: 24170,
                          pickup_geometry: {
                              x: 3.5738825,
                              y: 6.483704700000001
                          },
                          destination_geometry: {
                              x: 3.443095599999999,
                              y: 6.434032900000001
                          },
                          pickup_search_area_geometry: null,
                          city_id: 25,
                          origin_city_id: 25,
                          destination_city_id: 25,
                          route_availability_days: '["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]',
                          info: {
                              description: ''
                          },
                          slug: 'living-hope-parish-to-evertyone-tower',
                          route_availability_start_date: '2023-04-11T00:00:00.000Z',
                          route_availability_end_date: null,
                          blacklisted_availability_days: null,
                          is_exclusive: 0,
                          route_pair_id: null,
                          tag: 'fastest',
                          shuttle_request_id: null,
                          payer: 'passenger',
                          payment_mode: 'pre-trip',
                          owner_type: 'system',
                          owner_id: null,
                          blacklisted_availability_days_list: []
                      },
                      vehicle: {
                          id: 357,
                          brand: 'Toyota',
                          name: 'Corolla',
                          type: 'Sedan',
                          seats: 4,
                          registration_number: 'KTU-774FN',
                          amenities: 'AC',
                          created_at: '2022-05-24 15:19:09',
                          updated_at: '2023-01-31 10:30:08',
                          code: 'KTU774',
                          tracker_provider_id: null,
                          tracking_id: null,
                          partner_id: null,
                          vehicle_type_id: 4,
                          year: null,
                          status: 'active',
                          license_verification_status: 'not_submitted',
                          owner_driver_id: null,
                          inventory_type: 'regular'
                      },
                      trip: {
                          id: 59127,
                          route_id: 322,
                          driver_id: 964,
                          start_trip: '2024-02-12 09:23:00',
                          end_trip: '2024-02-12 09:31:11',
                          pickup_coordinate: '6.483704700000001, 3.5738825',
                          destination_coordinate: '6.5135466666661115, 3.3668908333333337',
                          created_at: '2024-02-12 09:23:01',
                          updated_at: '2024-02-12 09:31:12',
                          route_day_id: 4960417,
                          vehicle_id: 357,
                          cost_of_supply: null,
                          currency: 'NGN',
                          is_promoted: 0,
                          deleted_at: null,
                          restored_at: null
                      },
                      itinerary: {
                          id: 1960,
                          pickup_id: 98167,
                          route_id: 322,
                          departure_time: '09:30',
                          time_of_day: 'AM',
                          created_at: '2021-01-02 20:08:30',
                          updated_at: '2024-02-12 09:13:00',
                          restored_at: null,
                          deleted_at: null,
                          default_fare: 650,
                          default_fare_currency: 'NGN',
                          trip_time_in_hours: 93000,
                          pricing_scheme: 'per_seat',
                          pricing_margin: 20,
                          pricing_margin_unit: 'percent',
                          pricing_type: 'margin_value_generated',
                          break_even_utilization: 0.7,
                          payment_mode: 'pre-trip',
                          payer: 'passenger',
                          itinerary_pair_id: null,
                          trip_time: '09:30 AM'
                      },
                      pickup: {
                          id: 98172,
                          location: 'Living Hope Parish'
                      },
                      destination: {
                          id: 98158,
                          location: 'Okeira Kekere'
                      }
                  }
              ],
              metadata: {
                  total: 2,
                  current_page: 1,
                  limit: 10,
                  total_pages: 1
              }
          }
        )
        })
      })
    })
})
