export const user_fetch_response = {
    data: [
        {
            id: 49715,
            corporate_id: null,
            fname: 'Anthony',
            lname: 'Akpan',
            email: 'daniel.sumah+100@shuttlers.ng',
            phone: '08146923900',
            active: '1',
            avatar: null,
            code: '95b347b0-d0d5-11ee-a144-955b2cae5540-49715',
            created_at: '2024-02-21 17:23:45',
            updated_at: '2024-02-21 17:23:45',
            gender: 'female',
            dob: '2024-02-22 00:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42005,
                user_id: 49715,
                amount: '0',
                created_at: '2024-02-21 17:23:45',
                updated_at: '2024-02-21 17:23:45',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49714,
            corporate_id: 1,
            fname: 'Anthony',
            lname: 'Akpan',
            email: 'daniel.sumah+3@shuttlers.ng',
            phone: '08146923922',
            active: '1',
            avatar: null,
            code: '6fdfb190-d0d0-11ee-a144-955b2cae5540-49714',
            created_at: '2024-02-21 16:46:54',
            updated_at: '2024-02-21 16:46:54',
            gender: 'female',
            dob: '2024-02-23 00:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42004,
                user_id: 49714,
                amount: '0',
                created_at: '2024-02-21 16:46:54',
                updated_at: '2024-02-21 16:46:54',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49713,
            corporate_id: 141,
            fname: 'Saka',
            lname: 'Tinubu',
            email: 'saka@mailinator.com',
            phone: '08948473222',
            active: '1',
            avatar: null,
            code: '83fb7800-d0ce-11ee-a144-955b2cae5540-8MaxEsKQj',
            created_at: '2024-02-21 16:33:09',
            updated_at: '2024-02-21 16:33:39',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42003,
                user_id: 49713,
                amount: '0',
                created_at: '2024-02-21 16:33:09',
                updated_at: '2024-02-21 16:33:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49712,
            corporate_id: 141,
            fname: 'Aki',
            lname: 'One',
            email: 'aki1@mailinator.com',
            phone: '07060005555',
            active: '1',
            avatar: null,
            code: 'f3fe5520-d095-11ee-8725-972158efea1b--h57tquf93',
            created_at: '2024-02-21 09:48:16',
            updated_at: '2024-02-21 09:49:42',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-21T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42002,
                user_id: 49712,
                amount: '0',
                created_at: '2024-02-21 09:48:16',
                updated_at: '2024-02-21 09:48:16',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49711,
            corporate_id: 141,
            fname: 'Aki',
            lname: 'Main',
            email: 'aki@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: '026191b0-d094-11ee-8725-972158efea1b-DJ21jX3tDF',
            created_at: '2024-02-21 09:34:21',
            updated_at: '2024-02-21 09:42:59',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-21T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: '',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42001,
                user_id: 49711,
                amount: '0',
                created_at: '2024-02-21 09:34:21',
                updated_at: '2024-02-21 09:34:21',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49710,
            corporate_id: 141,
            fname: 'Oriaku',
            lname: 'Oby',
            email: 'oriaku@mailinator.com',
            phone: '09086543222',
            active: '1',
            avatar: null,
            code: 'e65659b0-cfd0-11ee-b821-9ff2fb64fd00-PyoR_p0zXV',
            created_at: '2024-02-20 10:17:42',
            updated_at: '2024-02-20 11:27:17',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-20T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42000,
                user_id: 49710,
                amount: '0',
                created_at: '2024-02-20 10:17:42',
                updated_at: '2024-02-20 10:17:42',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49709,
            corporate_id: 1,
            fname: 'folake',
            lname: 'apaokagi',
            email: 'folake1@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: 'c940fb10-cfc5-11ee-b821-9ff2fb64fd00-YW5Xpiih4h',
            created_at: '2024-02-20 08:58:09',
            updated_at: '2024-02-20 08:59:54',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41999,
                user_id: 49709,
                amount: '0',
                created_at: '2024-02-20 08:58:09',
                updated_at: '2024-02-20 08:58:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49708,
            corporate_id: 1,
            fname: 'invitefname',
            lname: 'lname',
            email: 'invite@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: 'a77eb6a0-cccf-11ee-b9d1-3dcad4e7640d-MD7T1J3nZR',
            created_at: '2024-02-16 14:31:13',
            updated_at: '2024-02-16 15:40:37',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-16T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41998,
                user_id: 49708,
                amount: '0',
                created_at: '2024-02-16 14:31:13',
                updated_at: '2024-02-16 14:31:13',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49707,
            corporate_id: null,
            fname: 'Ifiok',
            lname: 'Idiang',
            email: 'ifiok.idiang@gmail.com',
            phone: '08130648311',
            active: '1',
            avatar: null,
            code: 'ce4649d0-cb4c-11ee-8003-e70795f09cb7-49707',
            created_at: '2024-02-14 16:22:03',
            updated_at: '2024-02-15 10:23:13',
            gender: null,
            dob: '1993-02-09 23:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: 25,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-15T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'mobile',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41997,
                user_id: 49707,
                amount: '3150',
                created_at: '2024-02-14 16:22:03',
                updated_at: '2024-02-21 09:04:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49706,
            corporate_id: 141,
            fname: 'Voluptates',
            lname: 'Molestias',
            email: 'meg4@mailinator.com',
            phone: '08098787656',
            active: '1',
            avatar: null,
            code: 'cc1b6970-cb1e-11ee-a314-3bf6247d2d04-_FiKiEqraO',
            created_at: '2024-02-14 10:52:43',
            updated_at: '2024-02-14 10:54:36',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41996,
                user_id: 49706,
                amount: '0',
                created_at: '2024-02-14 10:52:43',
                updated_at: '2024-02-14 10:52:43',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        }
    ],
    metadata: {
        total: 41669,
        current_page: 1,
        limit: 10,
        total_pages: 4167
    }
}
export const user_create_response = {
    fname: 'Anthony',
    lname: 'Akpan',
    email: 'daniel.sumah+3@shuttlers.ng',
    phone: '08146923922',
    gender: 'female',
    dob: '2024-02-23 00:00:00.000',
    corporate_id: 1,
    country_code: 'NG',
    verified_at: null,
    code: '6fdfb190-d0d0-11ee-a144-955b2cae5540-49714',
    updated_at: '2024-02-21 16:46:54',
    created_at: '2024-02-21 16:46:54',
    id: 49714,
    active: '1',
    avatar: null,
    car_owner: '0',
    nfc_id: null,
    staff_id: null,
    client_id: null,
    location: null,
    city_id: null,
    login_remote_address: null,
    login_date_time: null,
    login_is_successful: null,
    blocked_reason: null,
    is_blocked: 0,
    blocked_at: null,
    sign_up_source: 'web',
    phone_verified_at: null,
    deleted_at: null,
    delete_reason: null,
    is_email_notification_enabled: 1,
    previous_corporate_id: null,
    date_removed_from_corporate: null,
    token: {
        iat: 1708530414,
        exp: 1740066414,
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbmFtZSI6IkFudGhvbnkiLCJsbmFtZSI6IkFrcGFuIiwiZW1haWwiOiJkYW5pZWwuc3VtYWgrM0BzaHV0dGxlcnMubmciLCJwaG9uZSI6IjA4MTQ2OTIzOTIyIiwiZ2VuZGVyIjoiZmVtYWxlIiwiZG9iIjoiMjAyNC0wMi0yMyAwMDowMDowMC4wMDAiLCJjb3Jwb3JhdGVfaWQiOjEsImNvdW50cnlfY29kZSI6Ik5HIiwidmVyaWZpZWRfYXQiOm51bGwsImNvZGUiOiI2ZmRmYjE5MC1kMGQwLTExZWUtYTE0NC05NTViMmNhZTU1NDAtNDk3MTQiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMi0yMSAxNjo0Njo1NCIsImNyZWF0ZWRfYXQiOiIyMDI0LTAyLTIxIDE2OjQ2OjU0IiwiaWQiOjQ5NzE0LCJhY3RpdmUiOiIxIiwiYXZhdGFyIjpudWxsLCJjYXJfb3duZXIiOiIwIiwibmZjX2lkIjpudWxsLCJzdGFmZl9pZCI6bnVsbCwiY2xpZW50X2lkIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwiY2l0eV9pZCI6bnVsbCwibG9naW5fcmVtb3RlX2FkZHJlc3MiOm51bGwsImxvZ2luX2RhdGVfdGltZSI6bnVsbCwibG9naW5faXNfc3VjY2Vzc2Z1bCI6bnVsbCwiYmxvY2tlZF9yZWFzb24iOm51bGwsImlzX2Jsb2NrZWQiOjAsImJsb2NrZWRfYXQiOm51bGwsInNpZ25fdXBfc291cmNlIjoid2ViIiwicGhvbmVfdmVyaWZpZWRfYXQiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImRlbGV0ZV9yZWFzb24iOm51bGwsImlzX2VtYWlsX25vdGlmaWNhdGlvbl9lbmFibGVkIjoxLCJwcmV2aW91c19jb3Jwb3JhdGVfaWQiOm51bGwsImRhdGVfcmVtb3ZlZF9mcm9tX2NvcnBvcmF0ZSI6bnVsbCwid2FsbGV0Ijp7ImFtb3VudCI6IjAiLCJ1c2VyX2lkIjo0OTcxNCwidXBkYXRlZF9hdCI6IjIwMjQtMDItMjEgMTY6NDY6NTQiLCJjcmVhdGVkX2F0IjoiMjAyNC0wMi0yMSAxNjo0Njo1NCIsImlkIjo0MjAwNCwiY3JlZGl0X2Ftb3VudCI6IjAiLCJpc19taWdyYXRlZF90b19jcmVkaXRfc3lzdGVtIjowfSwiaXNHdWVzdCI6ZmFsc2UsImlhdCI6MTcwODUzMDQxNCwiZXhwIjoxNzQwMDY2NDE0fQ.WSP4ZJ5li7OQPNGZp8NjAZyvMtBHrfuTGiZnTn2GX5o'
    },
    wallet: {
        amount: '0',
        user_id: 49714,
        updated_at: '2024-02-21 16:46:54',
        created_at: '2024-02-21 16:46:54',
        id: 42004,
        credit_amount: '0',
        is_migrated_to_credit_system: 0
    },
    isGuest: false
}

export const user_fetch_response_by_id = {
    id: 49715,
    corporate_id: null,
    fname: 'Anthony',
    lname: 'Akpan',
    email: 'daniel.sumah+100@shuttlers.ng',
    phone: '08146923900',
    active: '1',
    avatar: null,
    code: '95b347b0-d0d5-11ee-a144-955b2cae5540-49715',
    created_at: '2024-02-21 17:23:45',
    updated_at: '2024-02-21 21:17:38',
    gender: 'female',
    dob: '2024-02-22 00:00:00.000',
    car_owner: '0',
    nfc_id: null,
    staff_id: null,
    client_id: null,
    location: null,
    verified_at: null,
    city_id: null,
    login_remote_address: null,
    login_date_time: null,
    login_is_successful: null,
    blocked_reason: null,
    is_blocked: 0,
    blocked_at: null,
    sign_up_source: 'web',
    country_code: 'NG',
    phone_verified_at: null,
    deleted_at: null,
    delete_reason: null,
    is_email_notification_enabled: 1,
    previous_corporate_id: null,
    date_removed_from_corporate: null,
    wallet: {
        id: 42005,
        user_id: 49715,
        amount: '0.00',
        created_at: '2024-02-21 17:23:45',
        updated_at: '2024-02-21 17:23:45',
        credit_amount: 0,
        is_migrated_to_credit_system: 0,
        main_balance: '0'
    },
    isGuest: false,
    address: null
}
export const user_update_response = {}
export const user_active_booking_response = {}
