export const user_fetch_response = {
    data: [
        {
            id: 49715,
            corporate_id: null,
            fname: 'Anthony',
            lname: 'Akpan',
            email: 'daniel.sumah+100@shuttlers.ng',
            phone: '08146923900',
            active: '1',
            avatar: null,
            code: '95b347b0-d0d5-11ee-a144-955b2cae5540-49715',
            created_at: '2024-02-21 17:23:45',
            updated_at: '2024-02-21 17:23:45',
            gender: 'female',
            dob: '2024-02-22 00:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42005,
                user_id: 49715,
                amount: '0',
                created_at: '2024-02-21 17:23:45',
                updated_at: '2024-02-21 17:23:45',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49714,
            corporate_id: 1,
            fname: 'Anthony',
            lname: 'Akpan',
            email: 'daniel.sumah+3@shuttlers.ng',
            phone: '08146923922',
            active: '1',
            avatar: null,
            code: '6fdfb190-d0d0-11ee-a144-955b2cae5540-49714',
            created_at: '2024-02-21 16:46:54',
            updated_at: '2024-02-21 16:46:54',
            gender: 'female',
            dob: '2024-02-23 00:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42004,
                user_id: 49714,
                amount: '0',
                created_at: '2024-02-21 16:46:54',
                updated_at: '2024-02-21 16:46:54',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49713,
            corporate_id: 141,
            fname: 'Saka',
            lname: 'Tinubu',
            email: 'saka@mailinator.com',
            phone: '08948473222',
            active: '1',
            avatar: null,
            code: '83fb7800-d0ce-11ee-a144-955b2cae5540-8MaxEsKQj',
            created_at: '2024-02-21 16:33:09',
            updated_at: '2024-02-21 16:33:39',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42003,
                user_id: 49713,
                amount: '0',
                created_at: '2024-02-21 16:33:09',
                updated_at: '2024-02-21 16:33:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49712,
            corporate_id: 141,
            fname: 'Aki',
            lname: 'One',
            email: 'aki1@mailinator.com',
            phone: '07060005555',
            active: '1',
            avatar: null,
            code: 'f3fe5520-d095-11ee-8725-972158efea1b--h57tquf93',
            created_at: '2024-02-21 09:48:16',
            updated_at: '2024-02-21 09:49:42',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-21T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42002,
                user_id: 49712,
                amount: '0',
                created_at: '2024-02-21 09:48:16',
                updated_at: '2024-02-21 09:48:16',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49711,
            corporate_id: 141,
            fname: 'Aki',
            lname: 'Main',
            email: 'aki@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: '026191b0-d094-11ee-8725-972158efea1b-DJ21jX3tDF',
            created_at: '2024-02-21 09:34:21',
            updated_at: '2024-02-21 09:42:59',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-21T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: '',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42001,
                user_id: 49711,
                amount: '0',
                created_at: '2024-02-21 09:34:21',
                updated_at: '2024-02-21 09:34:21',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49710,
            corporate_id: 141,
            fname: 'Oriaku',
            lname: 'Oby',
            email: 'oriaku@mailinator.com',
            phone: '09086543222',
            active: '1',
            avatar: null,
            code: 'e65659b0-cfd0-11ee-b821-9ff2fb64fd00-PyoR_p0zXV',
            created_at: '2024-02-20 10:17:42',
            updated_at: '2024-02-20 11:27:17',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-20T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 42000,
                user_id: 49710,
                amount: '0',
                created_at: '2024-02-20 10:17:42',
                updated_at: '2024-02-20 10:17:42',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49709,
            corporate_id: 1,
            fname: 'folake',
            lname: 'apaokagi',
            email: 'folake1@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: 'c940fb10-cfc5-11ee-b821-9ff2fb64fd00-YW5Xpiih4h',
            created_at: '2024-02-20 08:58:09',
            updated_at: '2024-02-20 08:59:54',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41999,
                user_id: 49709,
                amount: '0',
                created_at: '2024-02-20 08:58:09',
                updated_at: '2024-02-20 08:58:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49708,
            corporate_id: 1,
            fname: 'invitefname',
            lname: 'lname',
            email: 'invite@mailinator.com',
            phone: '',
            active: '1',
            avatar: null,
            code: 'a77eb6a0-cccf-11ee-b9d1-3dcad4e7640d-MD7T1J3nZR',
            created_at: '2024-02-16 14:31:13',
            updated_at: '2024-02-16 15:40:37',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-16T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41998,
                user_id: 49708,
                amount: '0',
                created_at: '2024-02-16 14:31:13',
                updated_at: '2024-02-16 14:31:13',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49707,
            corporate_id: null,
            fname: 'Ifiok',
            lname: 'Idiang',
            email: 'ifiok.idiang@gmail.com',
            phone: '08130648311',
            active: '1',
            avatar: null,
            code: 'ce4649d0-cb4c-11ee-8003-e70795f09cb7-49707',
            created_at: '2024-02-14 16:22:03',
            updated_at: '2024-02-15 10:23:13',
            gender: null,
            dob: '1993-02-09 23:00:00.000',
            car_owner: '0',
            nfc_id: null,
            staff_id: null,
            client_id: null,
            location: null,
            verified_at: null,
            city_id: 25,
            login_remote_address: '172.22.2.0',
            login_date_time: '2024-02-15T00:00:00.000Z',
            login_is_successful: 1,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'mobile',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41997,
                user_id: 49707,
                amount: '3150',
                created_at: '2024-02-14 16:22:03',
                updated_at: '2024-02-21 09:04:09',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        },
        {
            id: 49706,
            corporate_id: 141,
            fname: 'Voluptates',
            lname: 'Molestias',
            email: 'meg4@mailinator.com',
            phone: '08098787656',
            active: '1',
            avatar: null,
            code: 'cc1b6970-cb1e-11ee-a314-3bf6247d2d04-_FiKiEqraO',
            created_at: '2024-02-14 10:52:43',
            updated_at: '2024-02-14 10:54:36',
            gender: null,
            dob: null,
            car_owner: '0',
            nfc_id: null,
            staff_id: '',
            client_id: null,
            location: null,
            verified_at: null,
            city_id: null,
            login_remote_address: null,
            login_date_time: null,
            login_is_successful: null,
            blocked_reason: null,
            is_blocked: 0,
            blocked_at: null,
            sign_up_source: 'web',
            country_code: 'NG',
            phone_verified_at: null,
            deleted_at: null,
            delete_reason: null,
            is_email_notification_enabled: 1,
            previous_corporate_id: null,
            date_removed_from_corporate: null,
            wallet: {
                id: 41996,
                user_id: 49706,
                amount: '0',
                created_at: '2024-02-14 10:52:43',
                updated_at: '2024-02-14 10:52:43',
                credit_amount: '0',
                is_migrated_to_credit_system: 0
            },
            isGuest: false
        }
    ],
    metadata: {
        total: 41669,
        current_page: 1,
        limit: 10,
        total_pages: 4167
    }
}
export const user_create_response = {
    fname: 'Anthony',
    lname: 'Akpan',
    email: 'daniel.sumah+3@shuttlers.ng',
    phone: '08146923922',
    gender: 'female',
    dob: '2024-02-23 00:00:00.000',
    corporate_id: 1,
    country_code: 'NG',
    verified_at: null,
    code: '6fdfb190-d0d0-11ee-a144-955b2cae5540-49714',
    updated_at: '2024-02-21 16:46:54',
    created_at: '2024-02-21 16:46:54',
    id: 49714,
    active: '1',
    avatar: null,
    car_owner: '0',
    nfc_id: null,
    staff_id: null,
    client_id: null,
    location: null,
    city_id: null,
    login_remote_address: null,
    login_date_time: null,
    login_is_successful: null,
    blocked_reason: null,
    is_blocked: 0,
    blocked_at: null,
    sign_up_source: 'web',
    phone_verified_at: null,
    deleted_at: null,
    delete_reason: null,
    is_email_notification_enabled: 1,
    previous_corporate_id: null,
    date_removed_from_corporate: null,
    token: {
        iat: 1708530414,
        exp: 1740066414,
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbmFtZSI6IkFudGhvbnkiLCJsbmFtZSI6IkFrcGFuIiwiZW1haWwiOiJkYW5pZWwuc3VtYWgrM0BzaHV0dGxlcnMubmciLCJwaG9uZSI6IjA4MTQ2OTIzOTIyIiwiZ2VuZGVyIjoiZmVtYWxlIiwiZG9iIjoiMjAyNC0wMi0yMyAwMDowMDowMC4wMDAiLCJjb3Jwb3JhdGVfaWQiOjEsImNvdW50cnlfY29kZSI6Ik5HIiwidmVyaWZpZWRfYXQiOm51bGwsImNvZGUiOiI2ZmRmYjE5MC1kMGQwLTExZWUtYTE0NC05NTViMmNhZTU1NDAtNDk3MTQiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMi0yMSAxNjo0Njo1NCIsImNyZWF0ZWRfYXQiOiIyMDI0LTAyLTIxIDE2OjQ2OjU0IiwiaWQiOjQ5NzE0LCJhY3RpdmUiOiIxIiwiYXZhdGFyIjpudWxsLCJjYXJfb3duZXIiOiIwIiwibmZjX2lkIjpudWxsLCJzdGFmZl9pZCI6bnVsbCwiY2xpZW50X2lkIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwiY2l0eV9pZCI6bnVsbCwibG9naW5fcmVtb3RlX2FkZHJlc3MiOm51bGwsImxvZ2luX2RhdGVfdGltZSI6bnVsbCwibG9naW5faXNfc3VjY2Vzc2Z1bCI6bnVsbCwiYmxvY2tlZF9yZWFzb24iOm51bGwsImlzX2Jsb2NrZWQiOjAsImJsb2NrZWRfYXQiOm51bGwsInNpZ25fdXBfc291cmNlIjoid2ViIiwicGhvbmVfdmVyaWZpZWRfYXQiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImRlbGV0ZV9yZWFzb24iOm51bGwsImlzX2VtYWlsX25vdGlmaWNhdGlvbl9lbmFibGVkIjoxLCJwcmV2aW91c19jb3Jwb3JhdGVfaWQiOm51bGwsImRhdGVfcmVtb3ZlZF9mcm9tX2NvcnBvcmF0ZSI6bnVsbCwid2FsbGV0Ijp7ImFtb3VudCI6IjAiLCJ1c2VyX2lkIjo0OTcxNCwidXBkYXRlZF9hdCI6IjIwMjQtMDItMjEgMTY6NDY6NTQiLCJjcmVhdGVkX2F0IjoiMjAyNC0wMi0yMSAxNjo0Njo1NCIsImlkIjo0MjAwNCwiY3JlZGl0X2Ftb3VudCI6IjAiLCJpc19taWdyYXRlZF90b19jcmVkaXRfc3lzdGVtIjowfSwiaXNHdWVzdCI6ZmFsc2UsImlhdCI6MTcwODUzMDQxNCwiZXhwIjoxNzQwMDY2NDE0fQ.WSP4ZJ5li7OQPNGZp8NjAZyvMtBHrfuTGiZnTn2GX5o'
    },
    wallet: {
        amount: '0',
        user_id: 49714,
        updated_at: '2024-02-21 16:46:54',
        created_at: '2024-02-21 16:46:54',
        id: 42004,
        credit_amount: '0',
        is_migrated_to_credit_system: 0
    },
    isGuest: false
}

export const user_fetch_response_by_id = {
    id: 49715,
    corporate_id: null,
    fname: 'Anthony',
    lname: 'Akpan',
    email: 'daniel.sumah+100@shuttlers.ng',
    phone: '08146923900',
    active: '1',
    avatar: null,
    code: '95b347b0-d0d5-11ee-a144-955b2cae5540-49715',
    created_at: '2024-02-21 17:23:45',
    updated_at: '2024-02-21 21:17:38',
    gender: 'female',
    dob: '2024-02-22 00:00:00.000',
    car_owner: '0',
    nfc_id: null,
    staff_id: null,
    client_id: null,
    location: null,
    verified_at: null,
    city_id: null,
    login_remote_address: null,
    login_date_time: null,
    login_is_successful: null,
    blocked_reason: null,
    is_blocked: 0,
    blocked_at: null,
    sign_up_source: 'web',
    country_code: 'NG',
    phone_verified_at: null,
    deleted_at: null,
    delete_reason: null,
    is_email_notification_enabled: 1,
    previous_corporate_id: null,
    date_removed_from_corporate: null,
    wallet: {
        id: 42005,
        user_id: 49715,
        amount: '0.00',
        created_at: '2024-02-21 17:23:45',
        updated_at: '2024-02-21 17:23:45',
        credit_amount: 0,
        is_migrated_to_credit_system: 0,
        main_balance: '0'
    },
    isGuest: false,
    address: null
}

export const user_active_booking_response = [
    {
        id: 625793,
        user_id: 386,
        route_id: 592,
        pickup_id: 115516,
        destination_id: 123596,
        itinerary_id: 2984,
        created_at: '2024-02-22 15:35:30',
        updated_at: '2024-02-22 15:35:30',
        recurring: 0,
        current_week: 1,
        bus_pass: 'IKR104-13',
        cost: 0,
        start_date: '2024-02-23',
        end_date: '2024-02-23',
        with_return_trip: 0,
        deleted_at: null,
        is_checked_in: 0,
        booking_status: 'active',
        origin_point: null,
        destination_point: null,
        pickup_route_bus_stop_id: 115516,
        destination_route_bus_stop_id: 123596,
        origin_label: 'Palmgrove Bus Stop',
        destination_label: 'ELF Bus Stop',
        selected_days: [
            'Friday'
        ],
        booked_from: null,
        booked_by: 386,
        booked_by_admin_id: 19,
        booked_by_user_type: null,
        itinerary: {
            id: 2984,
            pickup_id: 115514,
            route_id: 592,
            departure_time: '3:29',
            time_of_day: 'PM',
            created_at: '2021-11-01 20:07:51',
            updated_at: '2024-02-22 15:31:11',
            restored_at: null,
            deleted_at: null,
            default_fare: 500,
            default_fare_currency: 'NGN',
            trip_time_in_hours: 152900,
            pricing_scheme: 'per_seat',
            pricing_margin: 50,
            pricing_margin_unit: 'percent',
            pricing_type: 'margin_value_generated',
            break_even_utilization: 0.7,
            payment_mode: 'pre-trip',
            payer: 'passenger',
            itinerary_pair_id: null,
            trip_time: '3:29 PM'
        },
        pickup: {
            id: 115516,
            route_id: 592,
            location: 'Palmgrove Bus Stop',
            location_description: 'Bus Stop',
            created_at: '2021-11-02 13:21:53',
            updated_at: '2021-11-02 13:21:53',
            bus_stop_id: 115516,
            kind: 'pickup',
            pick_up_id: 115516
        },
        destination: {
            id: 123596,
            pickup_id: 115516,
            location: 'ELF Bus Stop',
            location_description: 'Bus Stop',
            fare: 0,
            created_at: '2021-11-02 13:21:53',
            updated_at: '2021-11-02 13:21:53',
            bus_stop_id: 123596
        },
        routeSchedules: [
            {
                id: 913432,
                user_id: 386,
                route_id: 592,
                user_route_id: 625793,
                days_ids: '[6]',
                created_at: '2024-02-22 15:35:30',
                updated_at: '2024-02-22 15:35:30',
                day_id: 6,
                trip_date: '2024-02-23',
                trip_id: null,
                luggage_quantity: 0,
                payment_source: 'main_balance',
                unit_cost: 0,
                passenger_name: 'daodu ajit',
                restored_at: null,
                deleted_at: null,
                status: 'ACTIVE',
                check_in_status: 'pending',
                vehicle_id: 112,
                route_itinerary_id: 2984,
                route_day_id: 4960099,
                bus_pass: 'IKR104-13',
                is_multiple_seats_booking: 0,
                passenger_json: {
                    email: 'daoduajit@gmail.com',
                    fname: 'Daodu',
                    lname: 'Ajit',
                    phone: '07040040187',
                    fullname: 'Daodu Ajit'
                },
                bus_captain_id: null,
                is_refunded: 0,
                cancellation_reason: null,
                instant_payment_provider: 'paystack',
                corporate_id: null,
                meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":5360,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":5860,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960099,"actualChargeToBeRemitted":500,"paymentReference":null}]}',
                unit_cost_before_additional_charges: '0.00',
                user: {
                    id: 386,
                    corporate_id: 48,
                    fname: 'Daodu',
                    lname: 'Ajit',
                    email: 'daoduajit@gmail.com',
                    phone: '07040040187',
                    active: '1',
                    avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/user-386-6PjoUewulI.jpeg',
                    code: '8a4ed980-5262-11ee-8bd8-6bdae3e41835-386',
                    created_at: '2018-06-09 16:26:18',
                    updated_at: '2024-02-21 22:59:19',
                    gender: 'male',
                    dob: '2021-11-17 00:00:00.000',
                    car_owner: '0',
                    nfc_id: '0a5cbb60-2d8c-4c39-8639-56170e8e7ac5',
                    staff_id: '386',
                    client_id: null,
                    location: null,
                    verified_at: null,
                    city_id: null,
                    login_remote_address: '172.22.2.0',
                    login_date_time: '2024-02-21T00:00:00.000Z',
                    login_is_successful: 1,
                    blocked_reason: null,
                    is_blocked: 0,
                    blocked_at: null,
                    sign_up_source: null,
                    country_code: 'NG',
                    phone_verified_at: null,
                    deleted_at: null,
                    delete_reason: null,
                    is_email_notification_enabled: 1,
                    previous_corporate_id: null,
                    date_removed_from_corporate: null,
                    closest_busstop: null,
                    sales_agent_account_id: null,
                    account_number: null,
                    bank_name: null,
                    bank_account_name: null,
                    nin: null,
                    nin_verified_at: null,
                    referred_by_id: null,
                    isGuest: false
                }
            }
        ],
        destinationRouteBusStop: {
            id: 123596,
            name: 'ELF Bus Stop',
            geometry: {
                x: 3.4749627113342285,
                y: 6.431775933276524
            },
            route_id: 592,
            previous_route_bus_stop: null,
            next_route_bus_stop: null,
            place_id: 'manually_planted_bus_stop_1644238292602_ty0wx2GSE',
            created_at: '2022-02-07 12:51:33',
            updated_at: '2022-07-25 18:48:18',
            restored_at: null,
            deleted_at: null,
            city_id: 25,
            position: 22,
            h3_km5_area_hash: '87589c8a0ffffff',
            h3_m50_area_hash: '8d589c8a02d3d3f',
            is_pickup: 0,
            is_dropoff: 1
        },
        pickupRouteBusStop: {
            id: 115516,
            name: 'Palmgrove Bus Stop',
            geometry: {
                x: 3.367129862308502,
                y: 6.541031870091094
            },
            route_id: 592,
            previous_route_bus_stop: null,
            next_route_bus_stop: null,
            place_id: 'manually_planted_bus_stop_1635859313273_Xo79UVrRm',
            created_at: '2021-11-02 13:21:53',
            updated_at: '2022-07-25 18:48:33',
            restored_at: null,
            deleted_at: null,
            city_id: 25,
            position: 6,
            h3_km5_area_hash: '87589c9a2ffffff',
            h3_m50_area_hash: '8d589c9a2c5cdbf',
            is_pickup: 1,
            is_dropoff: 1
        },
        route: {
            id: 592,
            pickup: 'Ojota Bus Park, Ikorodu Road, Lagos, Nigeria',
            destination: 'ELF Bus Stop, Lekki-Epe Expressway, Lekki, Nigeria',
            pickup_coordinate: '6.5887932, 3.379104599999999',
            destination_coordinate: '6.4317653, 3.4749734',
            bounds: '{"northeast":{"lat":6.588661,"lng":3.4749624},"southwest":{"lat":6.4300539,"lng":3.3648113}}',
            overview_polyline: '{"points":"ezeg@q_sS`UzNvIvFdAh@RLj@LzH`FrBrAjMjI`WlPdHtDzDvAbBl@tEjAjFx@~Fb@xI@tZQ|BL`GH`GIlE?hB?JpF?dCqEHQSMOIKU]CuE@gFZgCVgAj@k@`@Yx@Kd@Fl@XPn@LvB?xCsABoD@qGCwOFcSNyL?yBG}Gq@qGsAq@SUJKNA\\\\BRp@J`ATtDt@lEl@bDTfC?xCBxKCvf@YbZOpIIlME|P@f@A@VAWd@?xA@~FGhBCrDEvEGdJInPKbIEzKDhG?lEYnWMlMInDAtCDhCFbEC~JKvAFr@OdAQzGgBfGyBqEcNEk@RcBpB{FhBiGhAsCnAkAvDsAbHqBbOkErEwA`FsA^Kf@BhIfA|AVjBRvJrAdD\\\\vBNz@KhCy@~PoFpCy@VQRS^s@h@wAh@o@fTcGbFwArAs@|Aa@DMCIcCiHg@uB[_CMyBC_CViEl@yDlAmDzByDxBiCfBeBnAkAXYl@[TMlA_ApByAnF_EvBw@bCUzAFzBl@|DdBZF`JbEnDzAjC|@|EvAzBd@d@J~HfAjGh@bAFrAFfADlJG~DQtFi@|GcA`LsCfE{A|G_E|EwDpGoHxBoCnAcB|EoIbBcEj@wB~@yF\\\\eFT_Ib@_FlAsEvA_C~@cAjB_BhBcA|C}@rC_@vCEbCNdRnB`TbCbEz@vC`AzBbA|DvC`DrDhAjBz@vBZnB@`C_AxBeApAwAdAs@d@k@f@Ub@DPRPX?TIvCaCfCgCn@wBv@sB|@gBpBoDjCyEvBmDhCkE|A{AxBsAdDeAtFaAzGc@~CCnC?^??QoG?sAH_DL_BA{BVsD~@{ChAQCYa@yAiDe@{BI{ABkA`@sBzDkJbAiDn@kDP_BLqC?{D]eF_CkQwBoJeFcOa@uBy@gGi@gPe@qEo@}D_B{GQiAKaBLyAf@gBn@eA|C}DhByDhFoLbDyE~@oB~BaFRm@]KkFvKmDxFaGfNeAbBcC~Cw@zA[~@M~@?tBXpBnBvI^rCVlC^hJd@hI\\\\zB^zBVIO_Aw@wFQgDSaIYsE{@uFw@gD_AqEKaBLyAf@gBn@eA|C}Dj@cA|DkJjAoCtDoFjEeJRm@pANJ@ZD`Im@|Ey@zAYvEs@|FkAxB_Az@YlB{A~DsDhCqCd@i@Ng@|@cI~@iHGeCLmAGsE[kIG{FSgJGyAGCEAMCaA??cE{ABsA??GEwBDvB?FrA?zAC?bEyFD}EJiKRmSZc@K[QQMLOZ]t@s@xIeH`EkDv@_Ah@_An@_Bn@{CJiDiCsa@yEsi@"}',
            distance: '31.73 km',
            duration: '37 mins',
            total_seats: 14,
            day_of_week: 'MON - FRI',
            created_at: '2021-11-01 20:07:51',
            updated_at: '2024-02-22 15:34:01',
            status: 1,
            fare: null,
            visibility: 'public',
            corporate_id: null,
            is_future_route: 0,
            support_luggage: 0,
            luggage_config_id: null,
            route_code: 'IKR104',
            pickup_route_bus_stop_id: 123609,
            destination_route_bus_stop_id: 123596,
            is_draft: 0,
            duration_value: 2235,
            distance_value: 31729,
            pickup_geometry: {
                x: 3.379104599999999,
                y: 6.5887932
            },
            destination_geometry: {
                x: 3.4749734,
                y: 6.4317653
            },
            pickup_search_area_geometry: null,
            city_id: 25,
            origin_city_id: 25,
            destination_city_id: 25,
            route_availability_days: '["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]',
            info: {
                description: ''
            },
            slug: 'ojota-bus-stop-to-elf-bus-stop',
            route_availability_start_date: null,
            route_availability_end_date: null,
            blacklisted_availability_days: null,
            is_exclusive: 1,
            route_pair_id: null,
            tag: 'old',
            shuttle_request_id: null,
            payer: 'owner',
            payment_mode: 'post-trip',
            owner_type: 'corporate',
            owner_id: 1,
            blacklisted_availability_days_list: [],
            driver: {
                id: 359,
                vehicle_id: 112,
                fname: 'ajit',
                lname: 'daodu',
                email: 'daoduajit@gmail.com',
                phone: '07046640187',
                avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/driver-359-Nees7zfSok.jpeg',
                code: 'b2be5ec0-cb9c-11ec-b432-153069e8d217-359',
                active: '1',
                created_at: '2021-04-14 23:05:19',
                updated_at: '2024-02-23 10:40:41',
                city_id: 1,
                login_remote_address: null,
                login_date_time: '2024-02-23T00:00:00.000Z',
                login_is_successful: 1,
                blocked_reason: null,
                is_blocked: 0,
                blocked_at: null,
                country_code: 'NG',
                restored_at: null,
                deleted_at: null,
                residential_address: ' Agungi Ajiran Road Lekki Penninsula II Lekki',
                dob: '21-09-2005',
                marital_status: 'Single',
                driving_experience_years: 3,
                gender: 'Male',
                locality: 'ikeja',
                approval_status: 'approved',
                verified_at: '2021-04-14T22:05:19.000Z',
                vehicle: {
                    id: 112,
                    brand: 'Toyota',
                    name: 'Space Wagon',
                    type: 'Mini Bus',
                    seats: 14,
                    registration_number: '123-4567',
                    amenities: 'AC',
                    created_at: '2021-04-14 23:06:57',
                    updated_at: '2023-04-11 14:52:08',
                    code: null,
                    tracker_provider_id: null,
                    tracking_id: null,
                    partner_id: null,
                    vehicle_type_id: 5,
                    year: null,
                    status: 'active',
                    license_verification_status: 'not_submitted',
                    owner_driver_id: null,
                    inventory_type: 'regular',
                    vehicle_type: {
                        id: 5,
                        name: 'Mini Bus',
                        created_at: '2022-11-01 08:43:57',
                        updated_at: '2023-04-11 14:49:46',
                        description: '14-17 seater capacity vehicle',
                        image: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/admin-bmvHWIGqu0.jpeg',
                        cost_of_supply: null,
                        currency: 'NGN',
                        break_even_utilization: 1,
                        pricing_margin: 15,
                        pricing_margin_unit: 'percent'
                    }
                }
            }
        },
        user: {
            id: 386,
            fname: 'Daodu',
            lname: 'Ajit',
            email: 'daoduajit@gmail.com',
            phone: '07040040187',
            country_code: 'NG'
        },
        payment_source: 'main_balance',
        is_multiple_seats_booking: 0,
        duration_in_weeks: 0
    },
    {
        id: 625636,
        user_id: 386,
        route_id: 212,
        pickup_id: 106842,
        destination_id: 106888,
        itinerary_id: 3003,
        created_at: '2024-02-06 09:31:46',
        updated_at: '2024-02-06 09:31:46',
        recurring: 0,
        current_week: 0,
        bus_pass: 'IKR96-17',
        cost: 1140,
        start_date: '2024-02-23',
        end_date: '2024-02-23',
        with_return_trip: 0,
        deleted_at: null,
        is_checked_in: 0,
        booking_status: 'active',
        origin_point: null,
        destination_point: null,
        pickup_route_bus_stop_id: 106842,
        destination_route_bus_stop_id: 106888,
        origin_label: 'Ojota',
        destination_label: 'Fadeyi',
        selected_days: [
            'Friday',
            'Friday'
        ],
        booked_from: null,
        booked_by: 386,
        booked_by_admin_id: null,
        booked_by_user_type: null,
        itinerary: {
            id: 3003,
            pickup_id: 109432,
            route_id: 212,
            departure_time: '10:35',
            time_of_day: 'AM',
            created_at: '2022-01-03 18:18:46',
            updated_at: '2022-09-15 10:16:09',
            restored_at: null,
            deleted_at: null,
            default_fare: 950,
            default_fare_currency: 'NGN',
            trip_time_in_hours: 103500,
            pricing_scheme: 'per_seat',
            pricing_margin: 20,
            pricing_margin_unit: 'percent',
            pricing_type: 'margin_value_generated',
            break_even_utilization: 0.7,
            payment_mode: 'pre-trip',
            payer: 'passenger',
            itinerary_pair_id: null,
            trip_time: '10:35 AM'
        },
        pickup: {
            id: 106842,
            route_id: 212,
            location: 'Ojota',
            location_description: 'Bus Stop',
            created_at: '2021-12-29 05:01:58',
            updated_at: '2021-12-29 05:01:58',
            bus_stop_id: 106842,
            kind: 'pickup',
            pick_up_id: 106842
        },
        destination: {
            id: 106888,
            pickup_id: 106842,
            location: 'Fadeyi',
            location_description: 'Bus Stop',
            fare: 570,
            created_at: '2021-12-29 05:01:58',
            updated_at: '2021-12-29 05:01:58',
            bus_stop_id: 106888
        },
        routeSchedules: [
            {
                id: 913277,
                user_id: 386,
                route_id: 212,
                user_route_id: 625636,
                days_ids: '[6]',
                created_at: '2024-02-06 09:31:46',
                updated_at: '2024-02-06 09:31:46',
                day_id: 6,
                trip_date: '2024-02-23',
                trip_id: null,
                luggage_quantity: 0,
                payment_source: 'main_balance',
                unit_cost: 570,
                passenger_name: 'daodu ajit',
                restored_at: null,
                deleted_at: null,
                status: 'ACTIVE',
                check_in_status: 'pending',
                vehicle_id: 457,
                route_itinerary_id: 3003,
                route_day_id: 4960397,
                bus_pass: 'IKR96-17',
                is_multiple_seats_booking: 1,
                passenger_json: {
                    email: 'daoduajit@gmail.com',
                    fname: 'Daodu',
                    lname: 'Ajit',
                    phone: '07040040187',
                    fullname: 'Daodu Ajit'
                },
                bus_captain_id: null,
                is_refunded: 0,
                cancellation_reason: null,
                instant_payment_provider: 'shuttlers_local_pay',
                corporate_id: null,
                meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":70,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":570,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960397,"actualChargeToBeRemitted":1000,"paymentReference":null}]}',
                unit_cost_before_additional_charges: '70.00',
                user: {
                    id: 386,
                    corporate_id: 48,
                    fname: 'Daodu',
                    lname: 'Ajit',
                    email: 'daoduajit@gmail.com',
                    phone: '07040040187',
                    active: '1',
                    avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/user-386-6PjoUewulI.jpeg',
                    code: '8a4ed980-5262-11ee-8bd8-6bdae3e41835-386',
                    created_at: '2018-06-09 16:26:18',
                    updated_at: '2024-02-21 22:59:19',
                    gender: 'male',
                    dob: '2021-11-17 00:00:00.000',
                    car_owner: '0',
                    nfc_id: '0a5cbb60-2d8c-4c39-8639-56170e8e7ac5',
                    staff_id: '386',
                    client_id: null,
                    location: null,
                    verified_at: null,
                    city_id: null,
                    login_remote_address: '172.22.2.0',
                    login_date_time: '2024-02-21T00:00:00.000Z',
                    login_is_successful: 1,
                    blocked_reason: null,
                    is_blocked: 0,
                    blocked_at: null,
                    sign_up_source: null,
                    country_code: 'NG',
                    phone_verified_at: null,
                    deleted_at: null,
                    delete_reason: null,
                    is_email_notification_enabled: 1,
                    previous_corporate_id: null,
                    date_removed_from_corporate: null,
                    closest_busstop: null,
                    sales_agent_account_id: null,
                    account_number: null,
                    bank_name: null,
                    bank_account_name: null,
                    nin: null,
                    nin_verified_at: null,
                    referred_by_id: null,
                    isGuest: false
                }
            },
            {
                id: 913278,
                user_id: 386,
                route_id: 212,
                user_route_id: 625636,
                days_ids: '[6]',
                created_at: '2024-02-06 09:31:46',
                updated_at: '2024-02-06 09:31:46',
                day_id: 6,
                trip_date: '2024-02-23',
                trip_id: null,
                luggage_quantity: 0,
                payment_source: 'main_balance',
                unit_cost: 570,
                passenger_name: 'anthony akpan',
                restored_at: null,
                deleted_at: null,
                status: 'ACTIVE',
                check_in_status: 'pending',
                vehicle_id: 457,
                route_itinerary_id: 3003,
                route_day_id: 4960397,
                bus_pass: 'IKR96-16',
                is_multiple_seats_booking: 1,
                passenger_json: {
                    email: '',
                    fname: 'Anthony',
                    lname: 'Akpan',
                    phone: '7046102880',
                    fullname: 'Anthony Akpan'
                },
                bus_captain_id: null,
                is_refunded: 0,
                cancellation_reason: null,
                instant_payment_provider: 'shuttlers_local_pay',
                corporate_id: null,
                meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":70,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":570,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960397,"actualChargeToBeRemitted":1000,"paymentReference":null}]}',
                unit_cost_before_additional_charges: '70.00',
                user: {
                    id: 386,
                    corporate_id: 48,
                    fname: 'Daodu',
                    lname: 'Ajit',
                    email: 'daoduajit@gmail.com',
                    phone: '07040040187',
                    active: '1',
                    avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/user-386-6PjoUewulI.jpeg',
                    code: '8a4ed980-5262-11ee-8bd8-6bdae3e41835-386',
                    created_at: '2018-06-09 16:26:18',
                    updated_at: '2024-02-21 22:59:19',
                    gender: 'male',
                    dob: '2021-11-17 00:00:00.000',
                    car_owner: '0',
                    nfc_id: '0a5cbb60-2d8c-4c39-8639-56170e8e7ac5',
                    staff_id: '386',
                    client_id: null,
                    location: null,
                    verified_at: null,
                    city_id: null,
                    login_remote_address: '172.22.2.0',
                    login_date_time: '2024-02-21T00:00:00.000Z',
                    login_is_successful: 1,
                    blocked_reason: null,
                    is_blocked: 0,
                    blocked_at: null,
                    sign_up_source: null,
                    country_code: 'NG',
                    phone_verified_at: null,
                    deleted_at: null,
                    delete_reason: null,
                    is_email_notification_enabled: 1,
                    previous_corporate_id: null,
                    date_removed_from_corporate: null,
                    closest_busstop: null,
                    sales_agent_account_id: null,
                    account_number: null,
                    bank_name: null,
                    bank_account_name: null,
                    nin: null,
                    nin_verified_at: null,
                    referred_by_id: null,
                    isGuest: false
                }
            }
        ],
        destinationRouteBusStop: {
            id: 106888,
            name: 'Fadeyi',
            geometry: {
                x: 3.367735370993614,
                y: 6.524166387660111
            },
            route_id: 212,
            previous_route_bus_stop: 106887,
            next_route_bus_stop: 106889,
            place_id: 'manually_planted_bus_stop_1634993374304_1k0mZ7c8X',
            created_at: '2021-12-29 05:01:58',
            updated_at: '2022-07-25 18:48:29',
            restored_at: null,
            deleted_at: null,
            city_id: 25,
            position: 7,
            h3_km5_area_hash: '87589c9b1ffffff',
            h3_m50_area_hash: '8d589c9b1a9197f',
            is_pickup: 1,
            is_dropoff: 1
        },
        pickupRouteBusStop: {
            id: 106842,
            name: 'Ojota',
            geometry: {
                x: 3.3785711,
                y: 6.5873161
            },
            route_id: 212,
            previous_route_bus_stop: 109432,
            next_route_bus_stop: 106843,
            place_id: 'old_bus_stop_id_20',
            created_at: '2021-12-29 05:01:58',
            updated_at: '2022-11-07 07:17:12',
            restored_at: null,
            deleted_at: null,
            city_id: 25,
            position: 1,
            h3_km5_area_hash: '87588264bffffff',
            h3_m50_area_hash: '8d588264b396c7f',
            is_pickup: 1,
            is_dropoff: 0
        },
        route: {
            id: 212,
            pickup: 'Ojota, Ikorodu Road, Lagos, Nigeria',
            destination: 'Sandfill Bus Stop, Ozumba Mbadiwe Avenue, Lagos, Nigeria',
            pickup_coordinate: '6.5877167, 3.3785072',
            destination_coordinate: '6.4362473, 3.44192',
            bounds: '{"northeast":{"lat":6.5876773,"lng":3.4427207},"southwest":{"lat":6.422555399999999,"lng":3.366725}}',
            overview_polyline: '{"points":"_teg@_{rSfKtGzI|FtBrApAp@JF`@D|GjEpChBfQfLnPtK|BxA~BpAtCtA~@^bEvAfBd@pBb@~B`@fBTt@HxBPrAHfCArCB~JElC?hFGbOIzHChLGr`@UvGCjWOvMIrUM|h@Uhu@e@jD?xAHdABJHf@D^@NDn@AvBAjB?fBGl@?l@F`@It@MbAQlBo@jCo@|@a@nCaAx@UK]eCv@yHjCuBPu@AMHEF@VDFHDNDb@G`@IdAWhA_@jCo@xAm@lDkAK]{B{GiAiDCSAu@Jm@`A_Dr@oB~AuFVy@d@kAb@o@l@q@VOtBw@bHsBxGoBjGiBbBe@zBu@lEoAlAWxCVrF|@|@LhBRzAPzG`AdD\\\\bAJr@B\\\\A\\\\IhCy@fGsBhMuDp@m@FKXs@Tm@Zm@NORMrGeBlOkE~Ac@rAs@fBc@c@yA_BoEUw@Ka@a@_CS{BEgBB_CTgD^eC\\\\qAf@sAd@eArA_Ch@u@^a@xB_CfCaCp@m@XGb@[tB_BhCiBnB}Az@i@~@_@x@Qn@IbAGf@@dAJd@JfA\\\\xAp@~Ap@`@HH?fD`B~G~CnBt@zC`AfD~@b@HhB`@~HfAnIp@xCLhG@dH[tFi@`Em@zAUpBe@vCs@zEwAvAi@j@ShBcAjAo@fCcB|AiAnBgBxEmFpA_BhCaDbC{DzC}FnAyD`@gBh@}CNsANqBRmGN_ERwBPgAf@qBZaARa@v@mAj@s@|A{AdAu@t@a@nAg@dA[fASjAQjAGdAApABzBP`StBhALtKpAdCV`ANnBd@l@PxCdAbAb@|BxAjB~AfBpBz@hAt@pAb@~@Vv@R`AFl@D`AC~@Ul@i@jAa@l@c@b@w@n@sAz@SJWZW\\\\@DDPBFXJZG\\\\SxCcCz@eAt@o@VaAt@yBx@cBx@cBvCqFzC}EV]FCl@s@t@sAv@mAlAkARQl@a@B@D@D?HAFEFKBMEUOOICKAKOYe@y@kB]aAUcAMqAAoAF_AP{@Rq@~CoHd@qAVy@t@yCZcCPmBHeEE_BS}COwAk@oEeA_IKs@c@sB_A{De@{A@k@FW^Ot@g@|@qAXS`@MdAPpCVlCHlMAvSEdO@fOCrBDfDCCiDF}ED{GAQGKQOwKeEqHsC_Be@sBc@cAQwCYqCS}E]w@K]OQWCYQaAO?ODGFCBuFG_B?wH@_MAwF@oEJ{BTQkA_@iC[uAgAqEWyAMoACi@Bm@X{AVw@Te@fCcDn@y@\\\\k@x@oB|EcLtDoFVi@x@yAr@eB`AcCTe@[Kw@SIHGDEHAN@LBb@Yp@EJ"}',
            distance: '29.99 km',
            duration: '53 mins',
            total_seats: 14,
            day_of_week: 'MON - FRI',
            created_at: '2020-10-16 10:18:10',
            updated_at: '2024-01-12 11:09:22',
            status: 1,
            fare: null,
            visibility: 'public',
            corporate_id: null,
            is_future_route: 0,
            support_luggage: 0,
            luggage_config_id: null,
            route_code: 'IKR96',
            pickup_route_bus_stop_id: 106842,
            destination_route_bus_stop_id: 106994,
            is_draft: 0,
            duration_value: 3157,
            distance_value: 29990,
            pickup_geometry: {
                x: 3.3785072,
                y: 6.5877167
            },
            destination_geometry: {
                x: 3.44192,
                y: 6.4362473
            },
            pickup_search_area_geometry: null,
            city_id: 25,
            origin_city_id: 25,
            destination_city_id: 25,
            route_availability_days: '["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]',
            info: {
                description: ''
            },
            slug: 'ojota-to-sandfill-bus-stop-1',
            route_availability_start_date: '2023-04-11T00:00:00.000Z',
            route_availability_end_date: null,
            blacklisted_availability_days: null,
            is_exclusive: 0,
            route_pair_id: null,
            tag: 'old',
            shuttle_request_id: null,
            payer: 'passenger',
            payment_mode: 'pre-trip',
            owner_type: 'system',
            owner_id: null,
            blacklisted_availability_days_list: [],
            driver: {
                id: 1270,
                vehicle_id: 465,
                fname: 'Bobby',
                lname: 'James',
                email: 'bobby@mailinator.com',
                phone: '08076762211',
                avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/driver-1270-fpQ4YvIcpo.jpeg',
                code: null,
                active: '0',
                created_at: '2023-01-30 16:31:43',
                updated_at: '2024-01-11 07:25:29',
                city_id: null,
                login_remote_address: null,
                login_date_time: null,
                login_is_successful: null,
                blocked_reason: null,
                is_blocked: 0,
                blocked_at: null,
                country_code: 'NG',
                restored_at: null,
                deleted_at: null,
                residential_address: 'West Edmonton Mall, 170 Street Northwest, Edmonton, AB, Canada',
                dob: '1986-05-05',
                marital_status: null,
                driving_experience_years: null,
                gender: null,
                locality: null,
                approval_status: 'pending',
                verified_at: '2023-01-30T15:31:43.000Z',
                vehicle: {
                    id: 465,
                    brand: 'Toyota',
                    name: 'Hiace',
                    type: 'Mini Bus',
                    seats: 16,
                    registration_number: 'ACC-123XC',
                    amenities: null,
                    created_at: '2023-02-09 14:17:25',
                    updated_at: '2023-04-11 14:52:08',
                    code: null,
                    tracker_provider_id: null,
                    tracking_id: null,
                    partner_id: 175,
                    vehicle_type_id: 5,
                    year: 2014,
                    status: 'active',
                    license_verification_status: 'not_submitted',
                    owner_driver_id: null,
                    inventory_type: 'regular'
                },
                _pivot_driver_id: 1270,
                _pivot_route_itinerary_id: 3003
            }
        },
        user: {
            id: 386,
            fname: 'Daodu',
            lname: 'Ajit',
            email: 'daoduajit@gmail.com',
            phone: '07040040187',
            country_code: 'NG'
        },
        payment_source: 'main_balance',
        is_multiple_seats_booking: 1,
        exclude_self: false,
        users_booked_for: [
            {
                booking_status: 'active',
                user_id: 386,
                bus_pass: 'IKR96-16',
                itinerary_id: 3003,
                route_id: 212,
                user: {
                    email: '',
                    fname: 'Anthony',
                    lname: 'Akpan',
                    phone: '7046102880',
                    fullname: 'Anthony Akpan',
                    country_code: 'NG'
                }
            }
        ],
        duration_in_weeks: 0
    }
]

export const user_past_booking_response = [
{
    data: [
        {
            id: 913433,
            user_id: 386,
            route_id: 1291,
            user_route_id: 625794,
            days_ids: '[5]',
            created_at: '2024-02-22 17:54:48',
            updated_at: '2024-02-23 12:07:01',
            day_id: 5,
            trip_date: '2024-02-22',
            trip_id: 59142,
            luggage_quantity: 0,
            payment_source: 'main_balance',
            unit_cost: 570,
            passenger_name: 'daodu ajit',
            restored_at: null,
            deleted_at: null,
            status: 'COMPLETED',
            check_in_status: 'dropped-off',
            vehicle_id: 112,
            route_itinerary_id: 3705,
            route_day_id: 4960510,
            bus_pass: 'TEST12-14',
            is_multiple_seats_booking: 0,
            passenger_json: {
                email: 'daoduajit@gmail.com',
                fname: 'Daodu',
                lname: 'Ajit',
                phone: '07040040187',
                fullname: 'Daodu Ajit'
            },
            bus_captain_id: null,
            is_refunded: 0,
            cancellation_reason: null,
            instant_payment_provider: 'paystack',
            corporate_id: null,
            meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":70,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":570,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960510,"actualChargeToBeRemitted":500,"paymentReference":null}]}',
            unit_cost_before_additional_charges: '70.00',
            itinerary: {
                id: 3705,
                pickup_id: 4080,
                route_id: 1291,
                departure_time: '8:00',
                time_of_day: 'PM',
                created_at: '2022-08-03 16:11:43',
                updated_at: '2024-02-22 19:48:15',
                restored_at: null,
                deleted_at: null,
                default_fare: 10,
                default_fare_currency: 'NGN',
                trip_time_in_hours: 200000,
                pricing_scheme: 'per_seat',
                pricing_margin: 20,
                pricing_margin_unit: 'percent',
                pricing_type: 'margin_value_generated',
                break_even_utilization: 0.7,
                payment_mode: 'pre-trip',
                payer: 'passenger',
                itinerary_pair_id: null,
                trip_time: '8:00 PM'
            },
            userRoute: {
                id: 625794,
                user_id: 386,
                route_id: 1291,
                pickup_id: 129739,
                destination_id: 129740,
                itinerary_id: 3705,
                created_at: '2024-02-22 17:54:48',
                updated_at: '2024-02-23 12:06:42',
                recurring: 0,
                current_week: 1,
                bus_pass: 'IKIK584',
                cost: 570,
                start_date: '2024-02-22 00:00:00',
                end_date: '2024-02-22 00:00:00',
                with_return_trip: 0,
                deleted_at: null,
                is_checked_in: 1,
                booking_status: 'active',
                origin_point: null,
                destination_point: null,
                pickup_route_bus_stop_id: 129739,
                destination_route_bus_stop_id: 129740,
                origin_label: 'Agungi, Lekki - Epe Expressway, Lekki, Nigeria',
                destination_label: 'Ikeja City Mall, Obafemi Awolowo Way, Ojodu, Nigeria',
                selected_days: [
                    'Thursday'
                ],
                booked_from: null,
                booked_by: 386,
                booked_by_admin_id: 19,
                booked_by_user_type: null,
                itinerary: {
                    id: 3705,
                    pickup_id: 4080,
                    route_id: 1291,
                    departure_time: '8:00',
                    time_of_day: 'PM',
                    created_at: '2022-08-03 16:11:43',
                    updated_at: '2024-02-22 19:48:15',
                    restored_at: null,
                    deleted_at: null,
                    default_fare: 10,
                    default_fare_currency: 'NGN',
                    trip_time_in_hours: 200000,
                    pricing_scheme: 'per_seat',
                    pricing_margin: 20,
                    pricing_margin_unit: 'percent',
                    pricing_type: 'margin_value_generated',
                    break_even_utilization: 0.7,
                    payment_mode: 'pre-trip',
                    payer: 'passenger',
                    itinerary_pair_id: null,
                    trip_time: '8:00 PM'
                },
                destinationRouteBusStop: {
                    id: 129740,
                    name: 'Ikeja City Mall, Obafemi Awolowo Way, Ojodu, Nigeria',
                    geometry: {
                        x: 3.3581327,
                        y: 6.6143564
                    },
                    route_id: 1291,
                    previous_route_bus_stop: null,
                    next_route_bus_stop: null,
                    place_id: 'manually_planted_bus_stop_1659539503017_gzM78U-bA',
                    created_at: '2022-08-03 15:11:43',
                    updated_at: '2022-10-21 17:03:08',
                    restored_at: null,
                    deleted_at: null,
                    city_id: 25,
                    position: 6,
                    h3_km5_area_hash: '875882648ffffff',
                    h3_m50_area_hash: '8d588264898e17f',
                    is_pickup: 0,
                    is_dropoff: 1
                },
                pickup: {
                    kind: 'pickup',
                    created_at: '2024-02-23 15:41:50',
                    updated_at: '2024-02-23 15:41:50',
                    location: 'Agungi, Lekki - Epe Expressway, Lekki, Nigeria'
                },
                destination: {
                    created_at: '2024-02-23 15:41:50',
                    updated_at: '2024-02-23 15:41:50',
                    location: 'Ikeja City Mall, Obafemi Awolowo Way, Ojodu, Nigeria'
                },
                pickupRouteBusStop: {
                    id: 129739,
                    name: 'Agungi, Lekki - Epe Expressway, Lekki, Nigeria',
                    geometry: {
                        x: 3.5166148,
                        y: 6.437804900000001
                    },
                    route_id: 1291,
                    previous_route_bus_stop: null,
                    next_route_bus_stop: null,
                    place_id: 'manually_planted_bus_stop_1659539502984_gzM78U-bA',
                    created_at: '2022-08-03 15:11:43',
                    updated_at: '2022-08-03 15:11:43',
                    restored_at: null,
                    deleted_at: null,
                    city_id: 25,
                    position: 1,
                    h3_km5_area_hash: '87589c8acffffff',
                    h3_m50_area_hash: '8d589c8ac34d8ff',
                    is_pickup: 1,
                    is_dropoff: 0
                },
                driver: {
                    id: 1127,
                    vehicle_id: 280,
                    fname: 'Jaime',
                    lname: 'Dotun',
                    email: 'Dot.shuttlers@gmail.com',
                    phone: '08023333947',
                    avatar: null,
                    code: null,
                    active: '1',
                    created_at: '2022-07-01 15:06:06',
                    updated_at: '2023-04-13 11:44:38',
                    city_id: null,
                    login_remote_address: '172.20.33.54',
                    login_date_time: '2022-09-07T00:00:00.000Z',
                    login_is_successful: 1,
                    blocked_reason: null,
                    is_blocked: 0,
                    blocked_at: null,
                    country_code: 'NG',
                    restored_at: null,
                    deleted_at: null,
                    residential_address: null,
                    dob: null,
                    marital_status: null,
                    driving_experience_years: null,
                    gender: null,
                    locality: null,
                    approval_status: 'approved',
                    verified_at: '2022-07-01T14:06:06.000Z',
                    _pivot_driver_id: 1127,
                    _pivot_route_itinerary_id: 3705
                }
            },
            trip: {
                id: 59142,
                route_id: 1291,
                driver_id: 359,
                start_trip: '2024-02-22 19:53:11',
                end_trip: '2024-02-23 12:07:07',
                pickup_coordinate: '6.4406864, 3.5208242',
                destination_coordinate: '6.4405875, 3.5198445',
                created_at: '2024-02-22 19:53:12',
                updated_at: '2024-02-23 12:07:08',
                route_day_id: 4960510,
                vehicle_id: 112,
                cost_of_supply: 500,
                currency: 'NGN',
                is_promoted: 0,
                deleted_at: null,
                restored_at: null
            },
            vehicle: {
                id: 112,
                brand: 'Toyota',
                name: 'Space Wagon',
                type: 'Mini Bus',
                seats: 14,
                registration_number: '123-4567',
                amenities: 'AC',
                created_at: '2021-04-14 23:06:57',
                updated_at: '2023-04-11 14:52:08',
                code: null,
                tracker_provider_id: null,
                tracking_id: null,
                partner_id: null,
                vehicle_type_id: 5,
                year: null,
                status: 'active',
                license_verification_status: 'not_submitted',
                owner_driver_id: null,
                inventory_type: 'regular'
            },
            route: {
                id: 1291,
                pickup: 'Ikate Elegushi, Lekki, Nigeria',
                destination: 'Ikeja City Mall, Obafemi Awolowo Way, Ojodu, Nigeria',
                pickup_coordinate: '6.4398178, 3.488976',
                destination_coordinate: '6.6143564, 3.3581327',
                bounds: '{"northeast":{"lat":6.6157425,"lng":3.4908725},"southwest":{"lat":6.4301841,"lng":3.346607}}',
                distance: '36.10 km',
                duration: '60 mins',
                total_seats: null,
                day_of_week: 'MON - FRI',
                created_at: '2022-08-03 16:11:43',
                updated_at: '2024-02-22 17:54:07',
                status: 1,
                fare: null,
                visibility: 'public',
                corporate_id: null,
                is_future_route: 0,
                support_luggage: 0,
                luggage_config_id: null,
                route_code: 'TEST12',
                pickup_route_bus_stop_id: 129739,
                destination_route_bus_stop_id: 129740,
                is_draft: 0,
                duration_value: 3581,
                distance_value: 36105,
                pickup_geometry: {
                    x: 3.488976,
                    y: 6.4398178
                },
                destination_geometry: {
                    x: 3.3581327,
                    y: 6.6143564
                },
                pickup_search_area_geometry: null,
                city_id: 25,
                origin_city_id: 25,
                destination_city_id: 25,
                route_availability_days: '["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]',
                info: {
                    description: ''
                },
                slug: 'agungi-lekki-epe-expressway-lekki-to-ikeja-city-mall-obafemi-awolowo-way-ojodu',
                route_availability_start_date: '2023-04-11T00:00:00.000Z',
                route_availability_end_date: null,
                blacklisted_availability_days: '[]',
                is_exclusive: 0,
                route_pair_id: null,
                tag: 'old',
                shuttle_request_id: null,
                payer: 'passenger',
                payment_mode: 'pre-trip',
                owner_type: 'system',
                owner_id: null,
                blacklisted_availability_days_list: []
            },
            pickup: {
                id: 129739,
                location: 'Agungi, Lekki - Epe Expressway, Lekki, Nigeria'
            },
            destination: {
                id: 129740,
                location: 'Ikeja City Mall, Obafemi Awolowo Way, Ojodu, Nigeria'
            }
        },
        {
            id: 913430,
            user_id: 386,
            route_id: 592,
            user_route_id: 625791,
            days_ids: '[5]',
            created_at: '2024-02-22 15:27:05',
            updated_at: '2024-02-22 15:33:58',
            day_id: 5,
            trip_date: '2024-02-22',
            trip_id: 59141,
            luggage_quantity: 0,
            payment_source: 'main_balance',
            unit_cost: 0,
            passenger_name: 'daodu ajit',
            restored_at: null,
            deleted_at: null,
            status: 'COMPLETED',
            check_in_status: 'dropped-off',
            vehicle_id: 112,
            route_itinerary_id: 2984,
            route_day_id: 4960090,
            bus_pass: 'IKR104-13',
            is_multiple_seats_booking: 0,
            passenger_json: {
                email: 'daoduajit@gmail.com',
                fname: 'Daodu',
                lname: 'Ajit',
                phone: '07040040187',
                fullname: 'Daodu Ajit'
            },
            bus_captain_id: null,
            is_refunded: 0,
            cancellation_reason: null,
            instant_payment_provider: 'paystack',
            corporate_id: null,
            meta: '{"appliedCharges":[{"charge_type":"flat","charge_value":"500","type_slug":"seuns-ajo","additional_charge_id":26,"is_compulsory":1,"currency":"NGN","description":"Come and contribute to my life","actual_trip_fare":5360,"accumulated_fare_for_charge_type":500,"accumulated_charges_fare_with_trip":5860,"charge_type_fare_for_all_trips":500,"additional_charge_fare":500,"route_day_id":4960090,"actualChargeToBeRemitted":500,"paymentReference":null}]}',
            unit_cost_before_additional_charges: '0.00',
            itinerary: {
                id: 2984,
                pickup_id: 115514,
                route_id: 592,
                departure_time: '12:06',
                time_of_day: 'PM',
                created_at: '2021-11-01 20:07:51',
                updated_at: '2024-02-23 12:06:13',
                restored_at: null,
                deleted_at: null,
                default_fare: 500,
                default_fare_currency: 'NGN',
                trip_time_in_hours: 120600,
                pricing_scheme: 'per_seat',
                pricing_margin: 50,
                pricing_margin_unit: 'percent',
                pricing_type: 'margin_value_generated',
                break_even_utilization: 0.7,
                payment_mode: 'pre-trip',
                payer: 'passenger',
                itinerary_pair_id: null,
                trip_time: '12:06 PM'
            },
            userRoute: {
                id: 625791,
                user_id: 386,
                route_id: 592,
                pickup_id: 115518,
                destination_id: 123160,
                itinerary_id: 2984,
                created_at: '2024-02-22 15:27:05',
                updated_at: '2024-02-22 15:33:58',
                recurring: 0,
                current_week: 1,
                bus_pass: 'OJEL230',
                cost: 0,
                start_date: '2024-02-22 00:00:00',
                end_date: '2024-02-22 00:00:00',
                with_return_trip: 0,
                deleted_at: null,
                is_checked_in: 1,
                booking_status: 'completed',
                origin_point: null,
                destination_point: null,
                pickup_route_bus_stop_id: 115518,
                destination_route_bus_stop_id: 123160,
                origin_label: 'Jibowu Bus Stop',
                destination_label: 'Jasper Ike',
                selected_days: [
                    'Thursday'
                ],
                booked_from: null,
                booked_by: 386,
                booked_by_admin_id: 19,
                booked_by_user_type: null,
                itinerary: {
                    id: 2984,
                    pickup_id: 115514,
                    route_id: 592,
                    departure_time: '12:06',
                    time_of_day: 'PM',
                    created_at: '2021-11-01 20:07:51',
                    updated_at: '2024-02-23 12:06:13',
                    restored_at: null,
                    deleted_at: null,
                    default_fare: 500,
                    default_fare_currency: 'NGN',
                    trip_time_in_hours: 120600,
                    pricing_scheme: 'per_seat',
                    pricing_margin: 50,
                    pricing_margin_unit: 'percent',
                    pricing_type: 'margin_value_generated',
                    break_even_utilization: 0.7,
                    payment_mode: 'pre-trip',
                    payer: 'passenger',
                    itinerary_pair_id: null,
                    trip_time: '12:06 PM'
                },
                destinationRouteBusStop: {
                    id: 123160,
                    name: 'Jasper Ike',
                    geometry: {
                        x: 3.4587190126654788,
                        y: 6.427385189922534
                    },
                    route_id: 592,
                    previous_route_bus_stop: null,
                    next_route_bus_stop: null,
                    place_id: 'manually_planted_bus_stop_1643097268777_OlYFjpzB2',
                    created_at: '2022-01-25 07:54:29',
                    updated_at: '2022-07-25 18:49:05',
                    restored_at: null,
                    deleted_at: null,
                    city_id: 25,
                    position: 21,
                    h3_km5_area_hash: '87589c8a2ffffff',
                    h3_m50_area_hash: '8d589c8a284243f',
                    is_pickup: 1,
                    is_dropoff: 1
                },
                pickup: {
                    kind: 'pickup',
                    created_at: '2024-02-23 15:41:50',
                    updated_at: '2024-02-23 15:41:50',
                    location: 'Jibowu Bus Stop'
                },
                destination: {
                    created_at: '2024-02-23 15:41:50',
                    updated_at: '2024-02-23 15:41:50',
                    location: 'Jasper Ike'
                },
                pickupRouteBusStop: {
                    id: 115518,
                    name: 'Jibowu Bus Stop',
                    geometry: {
                        x: 3.3674490451812744,
                        y: 6.519469586765382
                    },
                    route_id: 592,
                    previous_route_bus_stop: null,
                    next_route_bus_stop: null,
                    place_id: 'manually_planted_bus_stop_1635859647001_xS77JZHwU',
                    created_at: '2021-11-02 13:27:27',
                    updated_at: '2022-07-25 18:48:46',
                    restored_at: null,
                    deleted_at: null,
                    city_id: 25,
                    position: 9,
                    h3_km5_area_hash: '87589c9b1ffffff',
                    h3_m50_area_hash: '8d589c9b10c933f',
                    is_pickup: 1,
                    is_dropoff: 1
                },
                driver: {
                    id: 359,
                    vehicle_id: 112,
                    fname: 'ajit',
                    lname: 'daodu',
                    email: 'daoduajit@gmail.com',
                    phone: '07046640187',
                    avatar: 'https://shuttlers-avatars-files.s3.us-east-2.amazonaws.com/driver-359-Nees7zfSok.jpeg',
                    code: 'b2be5ec0-cb9c-11ec-b432-153069e8d217-359',
                    active: '1',
                    created_at: '2021-04-14 23:05:19',
                    updated_at: '2024-02-23 14:46:01',
                    city_id: 1,
                    login_remote_address: null,
                    login_date_time: '2024-02-23T00:00:00.000Z',
                    login_is_successful: 1,
                    blocked_reason: null,
                    is_blocked: 0,
                    blocked_at: null,
                    country_code: 'NG',
                    restored_at: null,
                    deleted_at: null,
                    residential_address: ' Agungi Ajiran Road Lekki Penninsula II Lekki',
                    dob: '21-09-2005',
                    marital_status: 'Single',
                    driving_experience_years: 3,
                    gender: 'Male',
                    locality: 'ikeja',
                    approval_status: 'approved',
                    verified_at: '2021-04-14T22:05:19.000Z',
                    _pivot_driver_id: 359,
                    _pivot_route_itinerary_id: 2984
                }
            },
            trip: {
                id: 59141,
                route_id: 592,
                driver_id: 359,
                start_trip: '2024-02-22 15:31:31',
                end_trip: '2024-02-22 15:34:00',
                pickup_coordinate: '6.4409239, 3.5210001',
                destination_coordinate: '6.4408456, 3.5209012',
                created_at: '2024-02-22 15:31:31',
                updated_at: '2024-02-22 15:34:00',
                route_day_id: 4960090,
                vehicle_id: 112,
                cost_of_supply: 60000,
                currency: 'NGN',
                is_promoted: 0,
                deleted_at: null,
                restored_at: null
            },
            vehicle: {
                id: 112,
                brand: 'Toyota',
                name: 'Space Wagon',
                type: 'Mini Bus',
                seats: 14,
                registration_number: '123-4567',
                amenities: 'AC',
                created_at: '2021-04-14 23:06:57',
                updated_at: '2023-04-11 14:52:08',
                code: null,
                tracker_provider_id: null,
                tracking_id: null,
                partner_id: null,
                vehicle_type_id: 5,
                year: null,
                status: 'active',
                license_verification_status: 'not_submitted',
                owner_driver_id: null,
                inventory_type: 'regular'
            },
            route: {
                id: 592,
                pickup: 'Ojota Bus Park, Ikorodu Road, Lagos, Nigeria',
                destination: 'ELF Bus Stop, Lekki-Epe Expressway, Lekki, Nigeria',
                pickup_coordinate: '6.5887932, 3.379104599999999',
                destination_coordinate: '6.4317653, 3.4749734',
                bounds: '{"northeast":{"lat":6.588661,"lng":3.4749624},"southwest":{"lat":6.4300539,"lng":3.3648113}}',
                distance: '31.73 km',
                duration: '37 mins',
                total_seats: 14,
                day_of_week: 'MON - FRI',
                created_at: '2021-11-01 20:07:51',
                updated_at: '2024-02-22 15:34:01',
                status: 1,
                fare: null,
                visibility: 'public',
                corporate_id: null,
                is_future_route: 0,
                support_luggage: 0,
                luggage_config_id: null,
                route_code: 'IKR104',
                pickup_route_bus_stop_id: 123609,
                destination_route_bus_stop_id: 123596,
                is_draft: 0,
                duration_value: 2235,
                distance_value: 31729,
                pickup_geometry: {
                    x: 3.379104599999999,
                    y: 6.5887932
                },
                destination_geometry: {
                    x: 3.4749734,
                    y: 6.4317653
                },
                pickup_search_area_geometry: null,
                city_id: 25,
                origin_city_id: 25,
                destination_city_id: 25,
                route_availability_days: '["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]',
                info: {
                    description: ''
                },
                slug: 'ojota-bus-stop-to-elf-bus-stop',
                route_availability_start_date: null,
                route_availability_end_date: null,
                blacklisted_availability_days: null,
                is_exclusive: 1,
                route_pair_id: null,
                tag: 'old',
                shuttle_request_id: null,
                payer: 'owner',
                payment_mode: 'post-trip',
                owner_type: 'corporate',
                owner_id: 1,
                blacklisted_availability_days_list: []
            },
            pickup: {
                id: 115518,
                location: 'Jibowu Bus Stop'
            },
            destination: {
                id: 123160,
                location: 'Jasper Ike'
            }
        }

    ],
    metadata: {
        total: 250,
        current_page: 1,
        limit: 10,
        total_pages: 25
    }
}
]
