name: Auto Merge from hotfix to test and main

on:
  push:
    branches:
      - hotfix

jobs:
  merge-to-test-and-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important for accessing all history

      - name: Set up Git
        run: |
          git config --global user.name 'kromate'
          git config --global user.email 'akpananthony33@gmail.com'

      - name: Merge hotfix branch into test
        run: |
          git fetch origin test
          git checkout test
          git merge --no-ff origin/hotfix -m "Merging changes from hotfix to test"
          git push origin test

      - name: Merge hotfix branch into main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff origin/hotfix -m "Merging changes from hotfix to main"
          git push origin main
